/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as LayoutImport } from "./routes/_layout";
import { Route as IndexImport } from "./routes/index";
import { Route as SigninIndexImport } from "./routes/signin/index";
import { Route as LayoutDoctorsHomeIndexImport } from "./routes/_layout/doctors/home/index";
import { Route as LayoutDoctorsChatIndexImport } from "./routes/_layout/doctors/chat/index";

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
	id: "/_layout",
	getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
	path: "/",
	getParentRoute: () => rootRoute,
} as any);

const SigninIndexRoute = SigninIndexImport.update({
	path: "/signin/",
	getParentRoute: () => rootRoute,
} as any);

const LayoutDoctorsHomeIndexRoute = LayoutDoctorsHomeIndexImport.update({
	path: "/doctors/home/",
	getParentRoute: () => LayoutRoute,
} as any);

const LayoutDoctorsChatIndexRoute = LayoutDoctorsChatIndexImport.update({
	path: "/doctors/chat/",
	getParentRoute: () => LayoutRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexImport;
			parentRoute: typeof rootRoute;
		};
		"/_layout": {
			id: "/_layout";
			path: "";
			fullPath: "";
			preLoaderRoute: typeof LayoutImport;
			parentRoute: typeof rootRoute;
		};
		"/signin/": {
			id: "/signin/";
			path: "/signin";
			fullPath: "/signin";
			preLoaderRoute: typeof SigninIndexImport;
			parentRoute: typeof rootRoute;
		};
		"/_layout/doctors/chat/": {
			id: "/_layout/doctors/chat/";
			path: "/doctors/chat";
			fullPath: "/doctors/chat";
			preLoaderRoute: typeof LayoutDoctorsChatIndexImport;
			parentRoute: typeof LayoutImport;
		};
		"/_layout/doctors/home/": {
			id: "/_layout/doctors/home/";
			path: "/doctors/home";
			fullPath: "/doctors/home";
			preLoaderRoute: typeof LayoutDoctorsHomeIndexImport;
			parentRoute: typeof LayoutImport;
		};
	}
}

// Create and export the route tree

interface LayoutRouteChildren {
	LayoutDoctorsChatIndexRoute: typeof LayoutDoctorsChatIndexRoute;
	LayoutDoctorsHomeIndexRoute: typeof LayoutDoctorsHomeIndexRoute;
}

const LayoutRouteChildren: LayoutRouteChildren = {
	LayoutDoctorsChatIndexRoute: LayoutDoctorsChatIndexRoute,
	LayoutDoctorsHomeIndexRoute: LayoutDoctorsHomeIndexRoute,
};

const LayoutRouteWithChildren =
	LayoutRoute._addFileChildren(LayoutRouteChildren);

export interface FileRoutesByFullPath {
	"/": typeof IndexRoute;
	"": typeof LayoutRouteWithChildren;
	"/signin": typeof SigninIndexRoute;
	"/doctors/chat": typeof LayoutDoctorsChatIndexRoute;
	"/doctors/home": typeof LayoutDoctorsHomeIndexRoute;
}

export interface FileRoutesByTo {
	"/": typeof IndexRoute;
	"": typeof LayoutRouteWithChildren;
	"/signin": typeof SigninIndexRoute;
	"/doctors/chat": typeof LayoutDoctorsChatIndexRoute;
	"/doctors/home": typeof LayoutDoctorsHomeIndexRoute;
}

export interface FileRoutesById {
	__root__: typeof rootRoute;
	"/": typeof IndexRoute;
	"/_layout": typeof LayoutRouteWithChildren;
	"/signin/": typeof SigninIndexRoute;
	"/_layout/doctors/chat/": typeof LayoutDoctorsChatIndexRoute;
	"/_layout/doctors/home/": typeof LayoutDoctorsHomeIndexRoute;
}

export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths: "/" | "" | "/signin" | "/doctors/chat" | "/doctors/home";
	fileRoutesByTo: FileRoutesByTo;
	to: "/" | "" | "/signin" | "/doctors/chat" | "/doctors/home";
	id:
		| "__root__"
		| "/"
		| "/_layout"
		| "/signin/"
		| "/_layout/doctors/chat/"
		| "/_layout/doctors/home/";
	fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute;
	LayoutRoute: typeof LayoutRouteWithChildren;
	SigninIndexRoute: typeof SigninIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	LayoutRoute: LayoutRouteWithChildren,
	SigninIndexRoute: SigninIndexRoute,
};

export const routeTree = rootRoute
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/signin/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/doctors/chat/",
        "/_layout/doctors/home/"
      ]
    },
    "/signin/": {
      "filePath": "signin/index.tsx"
    },
    "/_layout/doctors/chat/": {
      "filePath": "_layout/doctors/chat/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/doctors/home/": {
      "filePath": "_layout/doctors/home/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
