/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SigninIndexImport } from './routes/signin/index'
import { Route as DoctorsHomeIndexImport } from './routes/doctors/home/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SigninIndexRoute = SigninIndexImport.update({
  path: '/signin/',
  getParentRoute: () => rootRoute,
} as any)

const DoctorsHomeIndexRoute = DoctorsHomeIndexImport.update({
  path: '/doctors/home/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/signin/': {
      id: '/signin/'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninIndexImport
      parentRoute: typeof rootRoute
    }
    '/doctors/home/': {
      id: '/doctors/home/'
      path: '/doctors/home'
      fullPath: '/doctors/home'
      preLoaderRoute: typeof DoctorsHomeIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninIndexRoute
  '/doctors/home': typeof DoctorsHomeIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninIndexRoute
  '/doctors/home': typeof DoctorsHomeIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/signin/': typeof SigninIndexRoute
  '/doctors/home/': typeof DoctorsHomeIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/signin' | '/doctors/home'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signin' | '/doctors/home'
  id: '__root__' | '/' | '/signin/' | '/doctors/home/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SigninIndexRoute: typeof SigninIndexRoute
  DoctorsHomeIndexRoute: typeof DoctorsHomeIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SigninIndexRoute: SigninIndexRoute,
  DoctorsHomeIndexRoute: DoctorsHomeIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/signin/",
        "/doctors/home/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/signin/": {
      "filePath": "signin/index.tsx"
    },
    "/doctors/home/": {
      "filePath": "doctors/home/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
